[opcache]
; Enable OPcache
opcache.enable = 1
opcache.enable_cli = 1

; Performance settings
opcache.memory_consumption = 256
opcache.interned_strings_buffer = 64
opcache.max_accelerated_files = 20000
opcache.max_wasted_percentage = 10

; File validation
opcache.validate_timestamps = 0
opcache.revalidate_freq = 0
opcache.save_comments = 1

; Optimization
opcache.fast_shutdown = 1
opcache.enable_file_override = 1
opcache.optimization_level = 0xffffffff

; JIT (Just In Time compilation)
opcache.jit_buffer_size = 100M
opcache.jit = tracing
